### ISSUE TITLE
Collisions between struct member names and generated Go code

### ISSUE THREAD

**Issue by mtourne** [capnproto/go-capnproto2#108] opened 2018-02-12 19:48 UTC
I'm compiling capnp idl files that are used in a C++ program, which almost works except on the toy example below.

It seems like the auto-generated String() method on structs collides with the member `String` as part of the struct `Variant`. In c++ this is not a problem since the automatically generated method is called `toString`.

Now I have to add an additional step to transform `string` into `stringMember`.
Maybe the capnp go compiler could be smarter about this?

Name collision example: 
```
@0xe28ef27e67ed9d7a;

using Go = import "/go.capnp";
$Go.package("name_collision");
$Go.import("code/go/test/proto/name_collision");

struct Variant {
  union {
    nil @0 :Void;
    boolean @1 :Bool;
    integer @2 :Int64;
    real @3 :Float64;
    string @4 :Text;
    binary @5 :Data;
    list @6 :List(Variant);
  }
}
```

```
package name_collision

import (
	"code/go/test/proto/name_collision"
	"zombiezen.com/go/capnproto2"
)

func main() {

}
```

```
$ go build code/go/test/proto/name_collision
# code/go/test/proto/name_collision
name_collision/main.go:4:2: imported and not used: "zombiezen.com/go/capnproto2" as capnp
name_collision/name_collision.capnp.go:115:6: Variant.String redeclared in this block
        previous declaration at name_collision/name_collision.capnp.go:66:6
name_collision/name_collision.capnp.go:115:6: method redeclared: Variant.String
        method(Variant) func() string
        method(Variant) func() (string, error)
```

**Comment by zombiezen** [comment] 2018-02-12 20:27
Dupe of #46.  As a workaround, you can add a `$Go.name` annotation to rename any generated symbol.

**Closed by zombiezen** 2018-02-12 20:27 UTC
Labels: bug, duplicate

**Comment by mtourne** [comment] 2018-02-12 23:34
Sorry for the duplication. 
I was looking for an annotation to help with this! but the documentation doesn't make explicit mention of it

**Comment by zombiezen** [comment] 2018-02-12 23:49
No worries!  Happy to accept doc fixes. :)
