### ISSUE TITLE
Error if attribute name "message" is used in a capnp struct definition

### ISSUE THREAD

**Issue by kfatehi** [capnproto/go-capnproto2#457] opened 2023-02-20 00:49 UTC
HI, thanks for the work on this library. I noticed what appears to be a bug. If I try to compile this file, [this struct](https://github.com/commaai/cereal/blob/b88523f05ac958f87a8f6d57c3f4bb20da55f216/log.capnp#L933-L941)'s "message" attribute causes the following error when trying to use the generated Go code later on.

```
cereal/gen/go/log.capnp.go:10674:26: AndroidLogEntry.Message redeclared in this block
        cereal/gen/go/log.capnp.go:10609:26: other declaration of Message
```

A quick workaround is naming it something else before generation

![image](https://user-images.githubusercontent.com/175305/219986222-fa32191b-f00f-4e5c-96d8-20c6f43bd596.png)

Would this be considered a bug in capnproto.org/go/capnp/v3 or bad practice by the author? I was unable to find a list of reserved words in the schema language, so I suspect this is sort of a de-facto reserved word if using capnproto.org/go/capnp/v3 at this point in time, correct? 

Thanks!

**Comment by zenhack** [comment] 2023-02-20 01:02
Yeah, this is a known issue; see #46. Besides renaming the field itself you can use the `$Go.name` annotation.

I'm going to go ahead and close this as a duplicate of #46.

**Comment by kfatehi** [comment] 2023-02-20 01:03
thanks! ill try to search more carefully next time

**Closed by zenhack** 2023-02-20 01:02 UTC
